### ISSUE TITLE
Research building custom Flatcar ISO with embedded Fabric installer

### ISSUE THREAD

**Issue by Frostman** [githedgehog/fabricator#115]

**Comment by mrbojangles3** [comment]
# Unified USB
This can be thought of in two parts - the payload and the delivery system.
The CI will make the devlivery system
hhfab will make the payload.
## The Delivery System:

A live usb image that can be written to any usb stick. This will contain a small partition, and a large partition. The small partition has all the things we need to boot a system, the dependencies of flatcar-install, and flatcar install.
The large partion has a bunch of empty space to hold the payload.
## The Payload:

hhfab will grab [a stable flatcar release](https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_image.bin.bz2) - using the steps mentioned [here](https://www.flatcar.org/docs/latest/installing/customizing-the-image/customize-the-image/). We might need to use some tools to resize the partitions in the image so we can fit all of the things we want on there.
hhfab will be responsible for modification of the flatcar image
hhfab will take the payload binary and write it to the second partition of the delivery system
hhfab will unmount the payload
hhfab will either create the usb for the user, or emit the correct cli instructions to do that. More user friendly to just write the iso for them.
## existing user experience hhfab workflow:

1. assuming the wiring yaml exists
1. hhfab init --preset lab --dev --wiring file1.yaml --wiring file2.yaml
1. hhfab build
1. user downloads flatcar
1. user writes it to a usb image
1. user boots physical hardware via sneakernet usb or virtual media
1. user via console or iKVM will scp control-install.tgz from hhfab machine to control node
1. user via console or iKVM will decompress, change into the dir, and sudo ./hhfab-recipe run
1. user via console or iKVM waits for success messge 01:35:15 INF Done took=3m39.586394608s

## proposed user experience hhfab workflow:

1. assuming the wiring yaml exists
1. hhfab build --preset lab --dev --wiring file1.yaml -> emits control_node.iso
1. hhfab prints instructions on how do dd the disk image  to a usb
1. user does something along the lines of dd if= ./hh_control_node.iso of=/dev/sdc bs=4k status=progress
1. user boots physical hardware via sneakernet usb or virtual media
1. user watches the boot and install output, but does not have to interact with the system
1. system will reboot and come up configured with hh packages

**Comment by mrbojangles3** [comment]
I have commented on https://github.com/flatcar/Flatcar/issues/945#issuecomment-2263256288
The next steps:
- [ ]  make and label the second partition of the live image
- [ ] ensure that when the live image boots and reaches multi-user.target that the second partition is mounted or accessible
- [ ] create a systemd unit file as a oneshot to install the image or use the ignition file to install

**Comment by mrbojangles3** [comment]
The last item in the check list will be taken care of at a later date. The oem ignition config can do a few things, that being one of them. 

A script that covers the creation of live-images is copied to the internal docs - https://github.com/githedgehog/docs-int/blob/master/src/image-build/howto.md
